#### **1. 넘파이 ndarray 개요**

In [5]:
import numpy as np
#넘파이 모듈 임포트, as np는 약어
#넘파이 기반 데이터 타입은 ndarray, ndarray를 이용해 넘파이에서 다차원 배열 생성 및 연산 수행

In [20]:
#넘파이 array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행

array1 = np.array([1,2,3])   #np.array(): ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)   #ndarray.shape는 ndarray의 차원과 크기를 튜플 형태로 나타냄. 1차원 배열, 3개의 데이터

array2 = np.array([[1,2,3],
                  [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)   #2차원 배열, 6개의 데이터

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)   #2차원 배열, 3개의 데이터. *array1과의 차이점: 차원. array3은 '1개의 행, 3개의 열'로 이루어짐.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [12]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
#리스트 []는 1차원, 리스트의 리스트 [[]]는 2차원

array1: 1차원, array2: 2차원, array3: 2차원


####
#### **2. ndarray의 데이터 타입**

In [17]:
#ndarray내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능
#한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음.

list1 = [1,2,3]
print(type(list1))   
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)   #list1은 모두 integer 숫자인 1,2,3을 값으로 가짐.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [18]:
#만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면, 데이터 크기가 더  큰 타입으로 형 변환을 일괄 적용.

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)   #list2은 integer 숫자인 1,2가 문자열 형태로 변환됨.

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)   #list3은 integer 숫자인 1,2가 float 형태로 변환됨.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [19]:
#astype() 메서드를 이용하여 ndarray 내 데이터값의 타입 변경도 가능

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


####
#### **3. ndarray를 편하게 생성하기 - arange, zeros, ones**

In [25]:
#ndarray를 연속값이나 0 또는 1로 초기화하는 경우
#arange()는 파이썬 range()와 유사
#default 함수 인자는 stop값

sequence_array = np.arange(10)   #0부터 9까지 생성
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [29]:
#zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
#ones()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))   #dtype을 지정하지 않았으므로, 기본값인 float64 형태로 반환.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


####
#### **4. ndarray의 차원과 크기를 변경하는 reshape()**

In [32]:
#reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환. 변환을 원하는 크기를 함수 인자로 부여.

array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
#지정된 사이즈로 변경이 불가능하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [35]:
#-1을 인자로 사용하면, 원래 ndarray와 호환되는 새로운 shape로 변환.
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)   #행 -1, 열 5. 고정된 5개의 열에 맞는 행을 자동으로 새롭게 생성해 변환해라.
print('array2 shape:',array2.shape)   #고정된 5개의 열에 맞는 행의 개수는 2.
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [36]:
#-1인자를 사용하더라도, 호환될 수 없는 형태는 변환할 수 없음.
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [37]:
#-1인자는 reshape(-1,1)와 같은 형태로 자주 사용됨. 예) stack, concat으로 결합할 때
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape((-1,1))
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape((-1,1))
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


####
#### **5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

**단일값 추출**

In [40]:
#한 개의 데이터만을 추출
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]sms 3번째 index 위치의 데이터값을 의미
value = array1[2]   #3번째 인덱스 위치의 데이터값을 의미
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [41]:
print('맨 뒤의 값:',array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [42]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [44]:
#다차원 ndarray에서 단일 값을 추출
#2차원의 경우 콤마로 분리된 행과 열의 인덱스를 통해 접근

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#####
**슬라이싱**

In [52]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [48]:
#슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략 가능

array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [49]:
#2차원 ndarray에서 슬라이싱으로 데이터에 접근

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n',array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n',array2d[1:3, 0:3])
print('array2d[1:3, :] \n',array2d[1:3, :])
print('array2d[:, :] \n',array2d[:, :])
print('array2d[:2, 1:] \n',array2d[:2, 1:])
print('array2d[:2, 0] \n',array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [50]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#####
**팬시 인덱싱**

In [55]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]   #(0,2), (1,2) 적용. 따라서 [3,6] 반환.
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]   #((0,0),(0,1)), ((1,0),(1,1)) 적용. 따라서 [[1,2],[4,5]] 반환.
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]   #((0:),(1:)) 적용. 따라서 [[1,2,3],[4,5,6]] 반환.
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#####
**불린 인덱싱**

In [56]:
#조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용됨.
#ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하기만 하면 됨.

array1d = np.arange(start=1, stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [60]:
array1d > 5
#5보다 큰 데이터가 있는 위치는 True값이, 그렇지 않은 경우는 False 값이 반환됨.
#조건을 걸면, False 인덱스는 무시하고, True 인덱스의 값에 해당하는 값만 반환됨. True 인덱스: [5,6,7,8], 데이터세트: [6,7,8,9]

array([False, False, False, False, False,  True,  True,  True,  True])

In [61]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [62]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


####
#### **6. 행렬의 정렬 - sort()와 argsort()**

**행렬 정렬**

In [65]:
#np.sort(): 넘파이에서 sort()를 호출하는 방식. - 원 해열ㄹ은 유지한 채, 원 행렬의 정렬된 행렬을 반환
#ndarray.sort(): 행렬 자체에서 sort()를 호출하는 방식. - 원 행렬 자체를 정렬한 상태로 반환하며 반환 값은 None.

org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [66]:
#sort()는 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬함.
#내림차순으로 정렬하기 위해서는 [::-1]을 적용. ex) np.sort().[::-1]

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [67]:
#행렬이 2차원 이상일 겨우 axis 축 값 설정을 통해 행 또는 열 방향으로 정려 수행 가능.
#열: axis=0, 행: axis=1

array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#####
**정렬된 행렬의 인덱스를 반환하기**

In [69]:
#np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 이용.
#np.argsort()를 이용해 원본 행렬의 정렬 시 행렬 인덱스 값 구하기

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [70]:
#내림차순 정렬 시 np.argsort()[::-1] 적용.

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [71]:
#argsort()는 넘파이에서 매우 활용도가 높음.

import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 추력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 추력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


####
#### **7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

**행렬 내적(행렬 곱)**

In [74]:
#행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산 가능.
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#####
**전치 행렬**

In [76]:
#전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬. transponpse().

A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
